platform :ios, '10.0'


target 'SwiftLiteKit_Example' do
    use_frameworks!

    pod 'SwiftLiteKit', :path => '../'
end

#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        target.build_configurations.each do |config|
#            config.build_settings['SWIFT_VERSION'] = '4.0'
#        end
#    end
#end

